name: Series Jobs

# Run this workflow on every push to the main branch
on:
  push:
    branches:
      - main  # Or 'master' depending on your default branch

jobs:
  job-1:
    name: Job 1
    runs-on: [testing, build]
    steps:
      - name: Output for Job 1
        run: echo "Hello from Job 1"

  job-2:
    name: Job 2
    runs-on: [build]
    needs:
      - job-1
    steps:
      - name: Output for Job 2
        run: echo "Hello from Job 2"

  job-3:
    name: Job 3
    runs-on: [deploy]
    needs:
      - job-1
    steps:
      - name: Output for Job 3
        run: echo "Hello from Job 3"

  job-4:
    name: Job 4
    runs-on: [build]
    needs:
      - job-2
      - job-3
    steps:
      - name: Output for Job 4
        run: echo "Hello from Job 4"
