name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: [build,deploy,testing]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image using buildx
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: my-actions/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/github-actions-app:1.0
